spring:
   datasource:
     url: jdbc:mysql://localhost:3306/blogapi?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
     username: root
     password: 12345
   jpa:
   hibernate: 
     ddl-auto: none
   show-sql: true
   properties: 
     hibernate: 
       dialect: org.hibernate.dialect.MySQL5Dialect
   json:
     serialization:
       WRITE_DATES_AS_TIMESTAMPS: false
     time-zone: UTC
app:
   jwtSecret: secret
   jwtExpirationInMs: 3600000
   
cors:
   allowedOrings: '*'